import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :phoenix_elxir_beam, PhoenixElxirBeamWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :phoenix_elxir_beam, PhoenixElxirBeamWeb.Endpoint,
  force_ssl: [
    hsts: true,
    rewrite_on: [:x_forwarded_proto],
    # `/health/*` is polled by the container / an external monitor and
    # `/metrics` scraped by Prometheus, both over plain HTTP on an internal
    # network; every other request is redirected to HTTPS. (`Plug.SSL`
    # `:exclude` matches `path_info` exactly, so each path is listed.)
    #
    # `black-phillip` (+ its Tailscale MagicDNS FQDN) is also excluded: this
    # tailnet doesn't support Tailscale-issued TLS certs, and traffic between
    # tailnet peers is already encrypted by Tailscale's own WireGuard tunnel,
    # so plain HTTP over Tailscale is not sending anything in the clear.
    exclude: [
      hosts: [
        "localhost",
        "127.0.0.1",
        "black-phillip",
        "black-phillip.tailcd1fdf.ts.net"
      ],
      paths: ["/health", "/health/live", "/health/ready", "/metrics"]
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# The MCP proxy plugin pipeline for prod. `ApprovalGate` holds egress for
# operator sign-off. The sidecar (Docker installs python3 + bakes priv/plugins)
# is skipped with a logged warning if python is absent.
config :phoenix_elxir_beam, PhoenixElxirBeam.MCP,
  plugins: [
    {PhoenixElxirBeam.MCP.Plugins.RuleEngine,
     config: %{
       "rules" => [
         %{
           "match" => %{"agent" => "agent://ci-runner", "tool_tags_any" => ["network_egress"]},
           "action" => "deny",
           "severity" => "high",
           "reason" => "policy: agent ci-runner may not perform network egress"
         }
       ]
     }},
    # Default-deny (M4.2): an untagged tool is held for operator sign-off. Set
    # "off" if you would rather curate tags before enforcement, or "deny" for a
    # hard refusal.
    {PhoenixElxirBeam.MCP.Plugins.UnclassifiedGuard, config: %{"mode" => "hold"}},
    {PhoenixElxirBeam.MCP.Plugins.TaintedArgGuard, []},
    {PhoenixElxirBeam.MCP.Plugins.BaselineGuard,
     config: %{
       "window_ms" => 10_000,
       "max_calls" => 5,
       "watch_tags" => ["sensitive_read"]
     }},
    {PhoenixElxirBeam.MCP.Plugins.ApprovalGate, []},
    {PhoenixElxirBeam.MCP.Plugins.TaintGuard, []},
    {PhoenixElxirBeam.MCP.Plugins.RugPull, []},
    {PhoenixElxirBeam.MCP.Plugins.SecretLeak, []},
    {PhoenixElxirBeam.MCP.Plugins.ProvenanceTaint, []},
    {PhoenixElxirBeam.MCP.Plugins.ResponseSizeGuard, []},
    {PhoenixElxirBeam.MCP.Plugins.StreamGuard, config: %{"max_bytes" => 1_200}},
    {PhoenixElxirBeam.MCP.Plugins.EventLogSink, []},
    {PhoenixElxirBeam.MCP.Plugins.StructuredLogSink, []},
    {
      :sidecar,
      # Provenance pin (M3.5) — the sidecar refuses to start if its script or
      # ruleset bytes change. Recompute both after editing either:
      #   mix run --no-start -e 'p = &Application.app_dir(:phoenix_elxir_beam, "priv/plugins/#{&1}"); IO.puts PhoenixElxirBeam.MCP.Plugin.Provenance.code_digest("python3", [p.("prompt_injection_scanner.py"), p.("injection_rules.json")])'
      # Add a `manifest:` entry too from the boot log to also pin its capabilities.
      # `limits` = best-effort kernel resource caps (Linux, needs `prlimit`); the
      # production-grade option is a container per sidecar — docs/plugin-supply-chain.md.
      name: "prompt-injection-scanner",
      transport: :stdio,
      cmd: "python3",
      args: [
        {:priv, "plugins/prompt_injection_scanner.py"},
        {:priv, "plugins/injection_rules.json"}
      ],
      config: %{},
      grants: %{block: true, mutate: [], network: false},
      pin: [code: "sha256:1f4fdb65e840362a5c000635e80e535b71930af63361f7be1c5c15a6ab3bb2d2"],
      limits: [as_mb: 512, cpu_s: 30]
    }
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
