import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :phoenix_elxir_beam, PhoenixElxirBeamWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :phoenix_elxir_beam, PhoenixElxirBeamWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# The MCP proxy plugin pipeline for prod. `ApprovalGate` holds egress for
# operator sign-off. The sidecar (Docker installs python3 + bakes priv/plugins)
# is skipped with a logged warning if python is absent.
config :phoenix_elxir_beam, PhoenixElxirBeam.MCP,
  plugins: [
    {PhoenixElxirBeam.MCP.Plugins.RuleEngine,
     config: %{
       "rules" => [
         %{
           "match" => %{"agent" => "agent://ci-runner", "tool_tags_any" => ["network_egress"]},
           "action" => "deny",
           "severity" => "high",
           "reason" => "policy: agent ci-runner may not perform network egress"
         }
       ]
     }},
    {PhoenixElxirBeam.MCP.Plugins.TaintedArgGuard, []},
    {PhoenixElxirBeam.MCP.Plugins.ApprovalGate, []},
    {PhoenixElxirBeam.MCP.Plugins.TaintGuard, []},
    {PhoenixElxirBeam.MCP.Plugins.RugPull, []},
    {PhoenixElxirBeam.MCP.Plugins.SecretLeak, []},
    {PhoenixElxirBeam.MCP.Plugins.EventLogSink, []},
    {PhoenixElxirBeam.MCP.Plugins.StructuredLogSink, []},
    {:sidecar,
     name: "prompt-injection-scanner",
     transport: :stdio,
     cmd: "python3",
     args: [{:priv, "plugins/prompt_injection_scanner.py"}],
     config: %{},
     grants: %{block: true, mutate: [], network: false}}
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
